# PYTHON İLE MAKİNE ÖĞRENMESİ
* Verilerin olduğu her alan makine öğrenmesi için uygundur.
* Makine öğrenmesi nerelerde kullanılır bakalım.
   * Bilgisayarda görme
   * Nesne tanıma 
   * Görüntü işleme
   * Sanal gerçeklik 
   * Virtual reality
   * Oyun
   * Arttırılmış gerçeklik
   * Ses tanıma
   * Robotlar ve Hareketleri
   * Pazarlama 
   * Müşteri ilişkileri memnuniyeti
   * Tavsiye Algoritmaları
   * Sağlık
   * Uydu görüntüleri yer bilimi
   * Sahtekarlık yakalama
   * Arama motorları
   * Endüstri 4.0
   * IoT  

#METODOLİJİ
1. Veri ön işleme 
2. Modelleme
 * Tahmin 
 * Doğrusal regresyon
 * Çoklu regresyon
 * Polinomal regresyon
 * Destek vektör ile tahmin
 * Karar ağacı ve tahmin
 * Rassal ağacı ve tahmin
 * Regresyon Modelleme
3. Evaluation
4. Deployment


#Veri Hazırlama

In [ ]:
#Kütüphanelerin yüklenmesi
import pandas as pd    # Veriler için kullandığımız kütüphane (Veri erişme,Düzgün şekilde tutabilme )
import numpy as np     # Büyük sayılar ve hesaplama için kullandığımız kütüphane
import matplotlib.pyplot as plt # Genellikle çizim için kullanılan kütüphane


In [ ]:
#Veri yükleme
veriler= pd.read_csv('veriler.csv' )   #Veri dosyamız .csv dosyasıdır. Verilerin arasında virgül olma durumu 

In [ ]:
print(veriler)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k


In [ ]:
print(veriler['boy'])

0     130
1     125
2     135
3     133
4     129
5     180
6     190
7     175
8     177
9     185
10    165
11    155
12    160
13    162
14    167
15    174
16    193
17    187
18    183
19    159
20    164
21    166
Name: boy, dtype: int64


# Python ile Nesneye Yönelik Programlama

* class ve object 
* Nesne yönelimli programlama, program içindeki öğeleri sınıflar ve nesneler olarak algılar.
* 


In [ ]:
class insan:     
  boy=180
  yaş=25
  def kilo(self,b): #
    return b - 5


ali = insan()   #ali insan objesi haline geldi
print(f'{ali.boy} cm')
print(ali.yaş)
print (ali.kilo(75))

180 cm
25
70


In [ ]:
# __init__(): --> metot yardımıyla sınıftan farklı nesneler oluşturulabilir.
class lise_sınıfları():
  def __init__(self,isim,sube,cinsiyet,ortalama):
    #yeni oluşturulan nesneyi ifade eder ve bir sınıfın yöntemleri ve nitelikleri de dahil olmak üzere tüm değişkenlerine hızlı bir şekilde erişmemizi sağlar. “self” parametresi ile her zaman “__init__” yöntemini kullanmamız gerekiyor.
    self.isim=isim
    self.sube=sube
    self.cinsiyet=cinsiyet
    self.ortalama=ortalama

In [ ]:
lise_sınıfları_ogr1=lise_sınıfları('eda','B','Kız','85,6')

In [ ]:
print(lise_sınıfları_ogr1.sube)
print(lise_sınıfları_ogr1.ortalama)
print(lise_sınıfları_ogr1.cinsiyet)

B
85,6
Kız


SİGORTA YAZILIMI
* Sigorta şirketi için şirket bilgileri alma ve sigortaya uygun kişileri bulmak
* Sigortaya uygun kişiler yaşları 60'dan küçük, geliri 6000 fazla ve kronik rahatsızlığı olmayan kişiler.

In [ ]:
class sigorta:

  def __init__(self,sirket_adi, kurulus_yili, kurucu_adi, sirket_slogan, calisan_sayisi, musteri):
    self.sirket_adi=sirket_adi
    self.kurulus_yili=kurulus_yili
    self.kurucu_adi=kurucu_adi
    self.sirket_slogan=sirket_slogan
    self.calisan_sayisi=calisan_sayisi
    self.musteri=musteri

  def yazdir(self):
    print(f'Şirket adı {self.sirket_adi}, Kuruluş yılı {self.kurulus_yili}, Kurucu adı {self.kurucu_adi}, Şirket sloganı {self.sirket_slogan}, Çalışan sayısı {self.calisan_sayisi}, Müşteri {self.musteri}')

  def sigorta_uygunlugu(self, yas, kronik_rahatsızlık, par):
    if yas >= 60 and kronik_rahatsızlık == True and par < 6000:
      print('sigorta için uygun değilsiniz')
    elif yas < 60 and par >= 6000 or kronik_rahatsızlık == False :
      print('sigorta için uygun')

  def sirket(self, yeni_num):
    self.sirket=yeni_num
    print(yeni_num)

In [ ]:
Bir_kişi = sigorta('Yazılım',2021,'Eda','Veri varsa gelecek var',15,'Özel şirket')


In [ ]:
Bir_kişi.yazdir()

Şirket adı Yazılım, Kuruluş yılı 2021, Kurucu adı Eda, Şirket sloganı Veri varsa gelecek var, Çalışan sayısı 15, Müşteri Özel şirket


In [ ]:
Bir_kişi.sigorta_uygunlugu(25, False, 6000 )

sigorta için uygun


In [ ]:
Bir_kişi.sirket(123654)

123654


LOJİSTİK ŞİRKET BİLGİ YAZILIMI
*Şirketler hakkında temel bilgiler alınır.

In [ ]:
class Lojistik:
  def __init__(self,sirket_ad, kurulus_yil, sirket_slogani, envanter_alanı):
    self.sirket_ad = sirket_ad
    self.kurulus_yil = kurulus_yil
    self.sirket_slogani = sirket_slogani
    self.envanter_alanı = envanter_alanı

  def yazdir(self):
    print(f"""ŞİRKET ADI: {self.sirket_ad}, KURULUŞ YILI: {self.kurulus_yil}, 
    SLOGANIMIZ: {self.sirket_slogani}, ENVANTERİMİZ: {self.envanter_alanı}""")

  def enventer_alan(self,degisken_enventer):
    self.degisken_enventer = degisken_enventer
    print(f'değişken enventerimiz : {self.degisken_enventer}')  

In [ ]:
lojistik1= Lojistik('EY YAZILIM', 2022 , 'Yenilikler sizler için var ', 2500 )

In [ ]:
lojistik1.enventer_alan(3000)

değişken enventerimiz : 3000


LOJİSTİK ŞİRKET BİLGİ YAZILIMI 2
* Şirketler hakkında temel bilgi alınır.
* Şirket gelir gider ve satış bilgileri alınır.
* Şirket geliri hesaplanır.

In [ ]:
class ticaret:
  def __init__(self,sirket_ad, kurulus_yil, sirket_slogani,satislar,giderler,gelir):
    self.sirket_ad = sirket_ad
    self.kurulus_yil = kurulus_yil
    self.sirket_slogani = sirket_slogani
    self.satislar = satislar
    self.giderler = giderler
    self.gelir = gelir

  def yazdir(self):
    print(f'SATIŞLAR: {self.satislar}, GİDERLER: {self.giderler}, GELİR {self.gelir}')

  def güncelleme(self,satislar,giderler):    #Şirkete girilen veriden sonra en son bir farklılık var ise güncellemisi buradan yaparız
    self.satislar = self.satislar + satislar
    self.giderler += giderler

  def işlem(self):
    self.gelir=self.satislar - self.giderler
    print(f'GELİRİMİZ: {self.gelir}')

In [ ]:
ticaret_1 = ticaret('E&YAZILIM', 2021,'Geleceğin daha iyi olması için E&YAZILIM', 200, 50, 150)

In [ ]:
ticaret_1.yazdir()

SATIŞLAR: 200, GİDERLER: 50, GELİR 150


In [ ]:
ticaret_1.güncelleme(300,100)

In [ ]:
ticaret_1.işlem()

GELİRİMİZ: 350


In [ ]:
ticaret_1.yazdir()

SATIŞLAR: 500, GİDERLER: 150, GELİR 350


#VERİLER (EKSİK VERİLER)
* Makine öğrenmesinde eksik veriler bize sıkıntı çıkartacağı için onlara bir çözüm bulmamız gerekir.

In [ ]:
eksik_veriler = pd.read_csv('eksikveriler.csv')

In [ ]:
print(eksik_veriler)

   ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k


In [ ]:
print(eksik_veriler['yas'])

0     10.0
1     11.0
2     10.0
3      9.0
4     12.0
5     30.0
6     25.0
7     35.0
8     22.0
9     33.0
10    27.0
11    44.0
12     NaN
13    41.0
14    55.0
15    47.0
16     NaN
17    27.0
18    28.0
19    29.0
20    32.0
21    42.0
Name: yas, dtype: float64


In [ ]:
from sklearn.impute  import SimpleImputer

imputer = SimpleImputer(missing_values= np.nan, strategy = 'mean' )  # SimpleImputer(missing_values= np.nan, strategy = 'bu kısma ne ile değiştirmek istiyoruz o yazılır' ) --> kalıp
yas = veriler.iloc[0:,1:4].values
print(yas)
imputer = imputer.fit(yas[0:,1:4]) # fit ile öğretiliyor. 
yas[:,1:4] = imputer.transform(yas[0:,1:4]) #transform ile öğrendiğinin uygulanması söyleniyor.
print(f'''yeni ----------
 {yas}''')

[[130  30  10]
 [125  36  11]
 [135  34  10]
 [133  30   9]
 [129  38  12]
 [180  90  30]
 [190  80  25]
 [175  90  35]
 [177  60  22]
 [185 105  33]
 [165  55  27]
 [155  50  44]
 [160  58  39]
 [162  59  41]
 [167  62  55]
 [174  70  47]
 [193  90  23]
 [187  80  27]
 [183  88  28]
 [159  40  29]
 [164  66  32]
 [166  56  42]]
yeni ----------
 [[130  30  10]
 [125  36  11]
 [135  34  10]
 [133  30   9]
 [129  38  12]
 [180  90  30]
 [190  80  25]
 [175  90  35]
 [177  60  22]
 [185 105  33]
 [165  55  27]
 [155  50  44]
 [160  58  39]
 [162  59  41]
 [167  62  55]
 [174  70  47]
 [193  90  23]
 [187  80  27]
 [183  88  28]
 [159  40  29]
 [164  66  32]
 [166  56  42]]


# Preparing data

In [ ]:
# İK departmanı, geçen ayki performanslarını değerlendirmek istiyor.
performanslar = open('şirket_performanslar.txt',"r")  #okuma modunu açıyoruz
veriler =performanslar.read() #dosya içeriğini okuyoruz

In [ ]:
print(veriler)

  Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.  
omer called 10 times and Sold 2 courses generated 60 dollars last month with a 6$ average deal size.
   KAren called 500 people and achieved success by GETting 24$ average deal size, got 12000 dollars revenue.     
Celine with 70 calls, made 2275 dollars and 32$ average deal size IN the previous month.  
     Sue called 100 people and earned 500 Dollars in REvenue and an AVERAGE DEAL SIZE of 5$ Last month.
Bora called 100 people generated 770 dollars last month, his average deal size was 25$.  
Rose made 600 phone calls and GENERATING 4000 dollars a past month 25$ average deal SIZE. 
Ellen made 800 calls and generated 6000 dollars a prior mONTH and reached 40$ the average deal size. 
 bob made 200 phone calls, helped to make a proGress and generated 800 dollars LAST MONTH and gaining 15$ average deal size.
Taylor, with 450 calls generated 1200 dollars in revenue pASt month, and the average deal s

In [ ]:
# Bu yöntem, dizeyi satır sonlarında böler ve bunları bir listede döndürür.
#splitlines()
performanslar = veriler.splitlines()
print(performanslar)

['  Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.  ', 'omer called 10 times and Sold 2 courses generated 60 dollars last month with a 6$ average deal size.', '   KAren called 500 people and achieved success by GETting 24$ average deal size, got 12000 dollars revenue.     ', 'Celine with 70 calls, made 2275 dollars and 32$ average deal size IN the previous month.  ', '     Sue called 100 people and earned 500 Dollars in REvenue and an AVERAGE DEAL SIZE of 5$ Last month.', 'Bora called 100 people generated 770 dollars last month, his average deal size was 25$.  ', 'Rose made 600 phone calls and GENERATING 4000 dollars a past month 25$ average deal SIZE. ', 'Ellen made 800 calls and generated 6000 dollars a prior mONTH and reached 40$ the average deal size. ', ' bob made 200 phone calls, helped to make a proGress and generated 800 dollars LAST MONTH and gaining 15$ average deal size.', 'Taylor, with 450 calls generated 1200 dollars in revenue pASt 

In [ ]:
satır = performanslar[0]
print(satır)
#Şimdi her satırın listenin bir öğesi olduğunu ve bir çalışana karşılık geldiğini görebiliriz

  Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.  


In [ ]:
#Dizenin kenarlarındaki boşlukları kaldıracaktır.
#strip()
satır = satır.strip(" ")   # ("buraya baştan silmek istediğiniz şeyleri yazıyoruz")
print(satır)

Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.


In [ ]:
# Tüm dizeyi küçük harfe çevrilecektir
#lower()
satır = satır.lower()
print(satır)

ben made 300 calls and generated 2400 dollars last month with an 8$ average deal size.


In [ ]:
# İlk harfin büyük olması için kullanılır.
#capitalize()
satır = satır.capitalize()
print(satır)

Ben made 300 calls and generated 2400 dollars last month with an 8$ average deal size.


In [ ]:
#Dizeyi bölmek ve her kelimeyi bir listede bir öğe olarak saklamak için kullanılır.
#split(" ")
tek_tek_Ayırmak = satır.split(" ")
print(tek_tek_Ayırmak)

['Ben', 'made', '300', 'calls', 'and', 'generated', '2400', 'dollars', 'last', 'month', 'with', 'an', '8$', 'average', 'deal', 'size.']


In [ ]:
print(tek_tek_Ayırmak[0])

Ben


In [ ]:
# 0 indekse baktığımızda isim tutuyor
isim = tek_tek_Ayırmak[0]

In [ ]:
print(tek_tek_Ayırmak[1])

made


In [ ]:
# 1 indeksten sonuç çıkartamadık. 2. indekse bakalım
print(tek_tek_Ayırmak[2])

300


In [ ]:
#Çalışanın yaptığı arama sayısı tutuyor
arama_sayısı = tek_tek_Ayırmak[2]

In [ ]:
#Ortalama anlaşma(gelir tutarını bulmak) boyutunu çıkarmak için '$' işareti kullanacağız.
for i in tek_tek_Ayırmak:
  if '$' in i:
    aranan_deger = i.split('$')[0]

print(aranan_deger)

8


In [ ]:
#Gelir tutarının indeksini bulalım.

dolar_indeksi = tek_tek_Ayırmak.index('dollars')
print(dolar_indeksi)

7


In [ ]:
#“dolar” kelimesinin geçtiği elementin indeksini bulalım.
#Bu ipucu yardımıyla, gelir tutarının indeksini bulmak için “dolar” unsurunun indeksinden 1 çıkarıyoruz.

gelir_indeksi = dolar_indeksi - 1
print(gelir_indeksi)

6


In [ ]:
gelir = tek_tek_Ayırmak[gelir_indeksi]
print(gelir)

2400


In [ ]:
print('İSİM: ', isim)
print('ARAMA SAYISI: ', arama_sayısı)
print('DOLAR İNDEKSİ: ', dolar_indeksi)
print('GELİR: ', gelir)

İSİM:  Ben
ARAMA SAYISI:  300
DOLAR İNDEKSİ:  7
GELİR:  2400


In [ ]:
dolar_indeksi = int(dolar_indeksi)
arama_sayısı = int(arama_sayısı)
gelir = int(gelir)

In [ ]:
print('İSİM: ', type(isim))
print('ARAMA SAYISI: ', type(arama_sayısı))
print('DOLAR İNDEKSİ: ', type(dolar_indeksi))
print('GELİR: ', type(gelir))

İSİM:  <class 'str'>
ARAMA SAYISI:  <class 'int'>
DOLAR İNDEKSİ:  <class 'int'>
GELİR:  <class 'int'>


In [ ]:
# Diğer verilerimizi de düzenlememiz gerekiyor.

isimler = []
arama_sayıları = []
dolar_indeksleri = []
gelirler = []

In [ ]:
def yeniden(performanslar):

 for satır in performanslar:
   satır = satır.strip(" ")
   satır = satır.lower()
   satır = satır.capitalize()

   tek_tek_Ayırmak = satır.split(" ")

   isim= tek_tek_Ayırmak[0]
   arama_sayısı = tek_tek_Ayırmak[2]

   for i in tek_tek_Ayırmak:
     if '$' in i:
       aranan_deger = i
       aranan_deger = i.split('$')[0]

   dolar_indeksi = tek_tek_Ayırmak.index('dollars')
   gelir_indeksi = dolar_indeksi - 1
   gelir=tek_tek_Ayırmak[gelir_indeksi]

   dolar_indeksi = int(dolar_indeksi)
   arama_sayısı = int(arama_sayısı)
   gelir = int(gelir)

   isimler.append(isim)
   arama_sayıları.append(arama_sayısı)
   dolar_indeksleri.append(dolar_indeksi)
   gelirler.append(gelir)

 return isimler, arama_sayıları, dolar_indeksleri, gelirler

In [ ]:
isimler, arama_sayiları, dolar_indeksleri, gelirler = yeniden(performanslar)

In [ ]:
print(f''' İSİMLER
{isimler}
ARAMA SAYILARI
{arama_sayıları}
DOLAR İNDEKSLERİ
{dolar_indeksleri}
GELİRLER
{gelirler}''' )

 İSİMLER
['Ben', 'Omer', 'Karen', 'Celine', 'Sue', 'Bora', 'Rose', 'Ellen', 'Bob', 'Taylor,', 'Jude']
ARAMA SAYILARI
[300, 10, 500, 70, 100, 100, 600, 800, 200, 450, 80]
DOLAR İNDEKSLERİ
[7, 10, 15, 6, 7, 6, 8, 7, 13, 6, 7]
GELİRLER
[2400, 60, 12000, 2275, 500, 770, 4000, 6000, 800, 1200, 500]


In [ ]:
print(len(isimler))

11


In [ ]:
IDler = list(range(0,11))
print(IDler)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
len(IDler)

11

In [ ]:
#Zip() yöntemi, bağımsız değişken olarak ilettiğiniz tüm değerlerin çiftler olarak depolandığı, yinelenebilir bir tanımlama grubu nesnesi oluşturur.
# dict ile IDler ile isimeri sözlüğe dönüştürdük (key,values)
değişkenler = dict(zip(IDler, isimler))
print(değişkenler)

{0: 'Ben', 1: 'Omer', 2: 'Karen', 3: 'Celine', 4: 'Sue', 5: 'Bora', 6: 'Rose', 7: 'Ellen', 8: 'Bob', 9: 'Taylor,', 10: 'Jude'}


In [ ]:
değişkenler_adları=dict(zip(gelirler,isimler))
print(değişkenler_adları)

{2400: 'Ben', 60: 'Omer', 12000: 'Karen', 2275: 'Celine', 500: 'Jude', 770: 'Bora', 4000: 'Rose', 6000: 'Ellen', 800: 'Bob', 1200: 'Taylor,'}


In [ ]:
#Gelir düzenini artana göre sıralama
#sorted
artan_sıralama = sorted(değişkenler_adları)
print(artan_sıralama)


[60, 500, 770, 800, 1200, 2275, 2400, 4000, 6000, 12000]


In [ ]:
artan_sıralama= sorted(değişkenler_adları)[0:3]
for i in artan_sıralama:
  print(değişkenler_adları[i])

Omer
Jude
Bora


In [ ]:
artan_sıralama = sorted(değişkenler_adları, reverse = True)[0:3]

for i in artan_sıralama:
  print(değişkenler_adları[i])

Karen
Ellen
Rose
